export const desktopInstallers = [
  {
    key: 'mac',
    name: 'macOS',
    href: '/install/releases/desktop/ZenMind-macOS-arm64.dmg',
    available: true,
    version: '0.2.4',
    zh: {
      label: 'macOS',
      button: '下载 macOS 版',
      summary: '适用于 Apple Silicon Mac 的 DMG 安装包',
      meta: ['DMG 安装包', 'arm64', '约 160 MB'],
      note: '打开 .dmg 后将 ZenMind 拖入“应用程序”文件夹。',
    },
    en: {
      label: 'macOS',
      button: 'Download for macOS',
      summary: 'DMG installer for Apple Silicon Macs.',
      meta: ['DMG installer', 'arm64', 'about 160 MB'],
      note: 'Open the .dmg and drag ZenMind into Applications.',
    },
  },
  {
    key: 'windows',
    name: 'Windows',
    href: '/downloads/ZenMind-0.2.3-x64.exe',
    available: true,
    version: '0.2.3',
    zh: {
      label: 'Windows',
      button: '下载 Windows 版',
      summary: '适用于 Windows x64 的 NSIS 安装包',
      meta: ['NSIS 安装包', 'x64', '保留用户数据卸载'],
      note: '运行安装包并按提示完成安装。',
    },
    en: {
      label: 'Windows',
      button: 'Download for Windows',
      summary: 'NSIS installer for Windows x64.',
      meta: ['NSIS installer', 'x64', 'data-safe uninstall'],
      note: 'Run the installer and follow the setup guide.',
    },
  },
  {
    key: 'linux',
    name: 'Linux',
    href: null,
    available: false,
    version: null,
    zh: {
      label: 'Linux',
      button: 'Linux 版暂未开放',
      summary: 'Desktop 安装包暂未提供 Linux 版本',
      meta: ['Desktop 包规划中', '可查看文档', '可访问源码'],
      note: '当前 Desktop 打包目标为 macOS DMG 与 Windows NSIS。',
    },
    en: {
      label: 'Linux',
      button: 'Linux build not available yet',
      summary: 'A Linux Desktop installer is not available yet.',
      meta: ['Desktop package planned', 'docs available', 'source available'],
      note: 'Current Desktop packaging targets are macOS DMG and Windows NSIS.',
    },
  },
];
