const siteUrl = 'https://www.zenmind.cc';
const githubUrl = 'https://github.com/linlay/zenmind';
const deployRepoUrl = 'https://github.com/linlay/zenmind-deploy';
const docsBaseUrl = 'https://github.com/linlay/zenmind/blob/main/docs';

export const externalLinks = {
  github: githubUrl,
  deployDocs: deployRepoUrl,
  deployRepo: deployRepoUrl,
  architecture: `${docsBaseUrl}/architecture.md`,
  agwui: `${docsBaseUrl}/agwui.md`,
  models: `${docsBaseUrl}/models.md`,
  mobile: `${docsBaseUrl}/mobile.md`,
  openAiNews: 'https://openai.com/news/',
  googleAiBlog: 'https://blog.google/technology/ai/',
  anthropicNews: 'https://www.anthropic.com/news',
  nvidiaAiNews: 'https://nvidianews.nvidia.com/news',
};

export const routeMap = {
  zh: {
    home: '/',
    download: '/download',
    documents: '/documents',
    news: '/news',
    market: '/market',
    login: '/login',
    profile: '/profile',
    adminLogin: '/admin/login',
    admin: '/admin',
    authFailure: '/auth/failure',
  },
  en: {
    home: '/en',
    download: '/en/download',
    documents: '/en/documents',
    news: '/en/news',
    market: '/en/market',
    login: '/en/login',
    profile: '/en/profile',
    adminLogin: '/en/admin/login',
    admin: '/en/admin',
    authFailure: '/en/auth/failure',
  },
};

export const desktopInstallers = [
  {
    key: 'mac',
    name: 'macOS',
    href: '/install/releases/desktop/ZenMind-macOS-arm64.dmg',
    available: true,
    version: '0.2.4',
    zh: {
      label: 'macOS',
      button: '下载 macOS 版',
      summary: '适用于 Apple Silicon Mac 的 DMG 安装包',
      meta: ['DMG 安装包', 'arm64', '约 160 MB'],
      note: '打开 .dmg 后将 ZenMind 拖入“应用程序”文件夹。',
    },
    en: {
      label: 'macOS',
      button: 'Download for macOS',
      summary: 'DMG installer for Apple Silicon Macs.',
      meta: ['DMG installer', 'arm64', 'about 160 MB'],
      note: 'Open the .dmg and drag ZenMind into Applications.',
    },
  },
  {
    key: 'windows',
    name: 'Windows',
    href: '/downloads/ZenMind-0.2.3-x64.exe',
    available: true,
    version: '0.2.3',
    zh: {
      label: 'Windows',
      button: '下载 Windows 版',
      summary: '适用于 Windows x64 的 NSIS 安装包',
      meta: ['NSIS 安装包', 'x64', '保留用户数据卸载'],
      note: '运行安装包并按提示完成安装。',
    },
    en: {
      label: 'Windows',
      button: 'Download for Windows',
      summary: 'NSIS installer for Windows x64.',
      meta: ['NSIS installer', 'x64', 'data-safe uninstall'],
      note: 'Run the installer and follow the setup guide.',
    },
  },
  {
    key: 'linux',
    name: 'Linux',
    href: null,
    available: false,
    version: null,
    zh: {
      label: 'Linux',
      button: 'Linux 版暂未开放',
      summary: 'Desktop 安装包暂未提供 Linux 版本',
      meta: ['Desktop 包规划中', '可查看文档', '可访问源码'],
      note: '当前 Desktop 打包目标为 macOS DMG 与 Windows NSIS。',
    },
    en: {
      label: 'Linux',
      button: 'Linux build not available yet',
      summary: 'A Linux Desktop installer is not available yet.',
      meta: ['Desktop package planned', 'docs available', 'source available'],
      note: 'Current Desktop packaging targets are macOS DMG and Windows NSIS.',
    },
  },
];

export const languages = {
  zh: {
    code: 'zh-CN',
    switchLabel: 'EN',
    brandMark: 'ZenMind',
    seo: {
      title: 'ZenMind | Desktop-first AI Agent 平台',
      description:
        'ZenMind 是以 Desktop 为入口的 AI Agent 平台，连接本地服务、Web/移动端工作流、国产模型生态与本地沙箱。',
      url: siteUrl,
    },
    nav: {
      home: '首页',
      download: '下载',
      documents: '文档',
      news: '新闻',
      market: '市场',
      login: '登录',
      adminLogin: '管理员登录',
      profile: '个人主页',
      admin: '管理后台',
      authFailure: '登录失败',
      github: 'GitHub',
    },
    theme: {
      label: '主题',
      auto: '自动',
      light: '白天',
      dark: '黑夜',
    },
    shared: {
      copyLabel: '复制',
      copiedLabel: '已复制',
      openGithub: 'GitHub',
      readDocs: '阅读文档',
      deployDocs: '部署入口',
      downloadDesktop: '下载',
      openProfile: '个人主页',
      logout: '退出登录',
      currentAccount: '当前账号',
      notSignedIn: '未登录',
      noPermission: '无权限',
      usagePreparing: '用量数据准备中',
      statusReady: '可用',
      statusSoon: '规划中',
      statusPreview: '预览',
      externalLabel: '打开外链',
      downloadFallback: '查看文档',
      downloadTotalPrefix: '总下载 ',
      downloadTotalSuffix: ' 次',
    },
    home: {
      eyebrow: 'Desktop-first AI Agent Platform',
      headline: '从桌面端进入你的 AI Agent 工作流',
      heroIntro:
        'ZenMind 把桌面端、本地服务、模型 Provider、沙箱环境和技能市场组织到同一套工作入口里，适合长期任务、文档处理和可控的 Agent 工作流。',
      primaryCta: '查看文档',
      secondaryCta: '登录 / 个人主页',
      downloadUnavailableTitle: '当前环境暂未提供 Desktop 安装包',
      downloadUnavailableBody: '你仍然可以查看文档或源码，了解 ZenMind Desktop、核心服务和本地沙箱的运行方式。',
      heroStats: [
        { value: 'Desktop', label: '统一安装、启动、监控' },
        { value: 'AGW UI', label: '流式输出、HITL、viewport' },
        { value: 'Sandbox', label: '长生命周期工具环境' },
      ],
      consoleTitle: 'ZenMind runtime',
      consoleLines: [
        'desktop: service center ready',
        'app-server: token bridge online',
        'agent-platform: AGW stream attached',
        'container-hub: sandbox session prepared',
      ],
      featuresEyebrow: '核心功能',
      featuresTitle: '核心能力一眼看懂',
      featuresIntro: '把原来偏长的功能叙事压缩成更易扫描的能力入口：Desktop、Agent UI、模型、沙箱和市场。',
      portalEyebrow: 'Portal',
      portalTitle: '你想做什么？',
      portalIntro: '首页不只做宣传，也直接把用户带到正确入口。',
      portalEntries: [
        {
          key: 'documents',
          title: '文档',
          body: '软件使用、开发集成、AGW UI、模型和沙箱说明。',
          href: '/documents',
        },
        {
          key: 'news',
          title: '新闻',
          body: '产品动态和 AI 行业观察。',
          href: '/news',
        },
        {
          key: 'market',
          title: '市场',
          body: '技能、沙箱、插件、模型 Provider 和工作流模板。',
          href: '/market',
        },
        {
          key: 'download',
          title: '下载',
          body: '按平台下载安装桌面端。',
          href: '/download',
        },
        {
          key: 'profile',
          title: '个人主页',
          body: '登录后查看账号状态和用量占位。',
          href: '/profile',
        },
      ],
      capabilityCards: [
        {
          key: 'desktop',
          title: 'Desktop',
          body: '统一安装、启动、监控和设置。',
        },
        {
          key: 'agent',
          title: 'Agent UI',
          body: '流式输出、人工确认和可恢复任务。',
        },
        {
          key: 'models',
          title: 'Models',
          body: '模型 Provider、能力标记和用量统计。',
        },
        {
          key: 'sandbox',
          title: 'Sandbox',
          body: '长期任务和工具执行环境。',
        },
        {
          key: 'market',
          title: 'Market',
          body: '技能、插件和工作流模板入口。',
        },
      ],
      featureSections: [
        {
          key: 'desktop',
          title: '一个 Desktop 应用管理整套运行时',
          body:
            'ZenMind Desktop 负责安装、初始化、启动、停止、服务健康监控和嵌入式 Web 表面，让用户从一个控制中心进入所有能力。',
          points: ['服务生命周期', '日志与设置', '身份令牌桥接'],
          visualTitle: 'Desktop 控制中心',
          visualRows: ['安装内置服务', '启动 Agent 运行时', '查看日志与健康状态'],
        },
        {
          key: 'models',
          title: '面向国产模型生态的运行时注册表',
          body:
            '优先支持 DeepSeek V4、MiMo、MiniMax M3、Qwen/百炼等模型方向，并保留 provider registry、模型能力和用量字段的扩展空间。',
          points: ['模型切换', 'reasoning 与 vision 标记', 'token/cache/cost usage'],
          visualTitle: '模型运行时注册表',
          visualRows: ['DeepSeek V4', 'MiMo', 'MiniMax M3', 'Qwen / Bailian'],
        },
        {
          key: 'agw',
          title: 'AGW UI 协议承载真实 Agent 交互',
          body:
            'AGW UI 结合 HTTP、SSE 与可选 WebSocket，支持流式输出、attach 续接、HITL、交互视图、usage 快照和子智能体调用。',
          points: ['H2A streaming', 'question / approval / form / plan', 'agent_invoke'],
          visualTitle: 'AGW UI 事件流',
          visualRows: ['流式增量输出', '等待人工确认', '渲染交互视图', '记录用量快照'],
        },
        {
          key: 'sandbox',
          title: '本地沙箱让工具和办公任务长期运行',
          body:
            'agent-container-hub 提供本地沙箱会话、环境模板和容器工具运行时，为文档、表格、PDF、PPT 等办公自动化保留稳定执行层。',
          points: ['长生命周期会话', '工具环境模板', 'Office 技能链路'],
          visualTitle: '本地沙箱',
          visualRows: ['容器会话', '工具运行时', 'DOCX / XLSX / PDF / PPT'],
        },
        {
          key: 'clients',
          title: '同一套 Agent 体验服务 Desktop、Web 与移动端',
          body:
            'Desktop 是入口，Web Client 渲染对话、Timeline、模型切换和 viewport；移动端方向复用同一 AGW UI 协议，而不是另起一套契约。',
          points: ['Desktop first', 'Web timeline', 'Mobile direction'],
          visualTitle: '同一套 Agent 契约',
          visualRows: ['Desktop 入口', 'Web Client', '移动端方向'],
        },
      ],
      finalCtaTitle: '开始使用 ZenMind',
      finalCtaBody: '先下载桌面端，或从文档和市场了解能力边界。',
      footerTagline: 'Desktop-first AI Agent platform for local, web, and mobile workflows.',
    },
    documents: {
      eyebrow: 'Documents',
      title: '文档',
      intro: '软件使用与开发说明的统一入口：先帮助用户完成下载、登录和使用，再承接架构、协议、模型、沙箱和能力市场说明。',
      sectionLabel: '文档分组',
      audienceLabel: '适合',
      actionLabel: '查看文档',
      docSections: [
        {
          title: '快速上手',
          intro: '面向第一次进入 ZenMind 的用户，覆盖下载、登录、个人主页与常见问题。',
          cards: [
            {
              title: '下载安装',
              body: '按平台选择桌面端安装包，了解 macOS、Windows 与 Linux 的当前可用状态。',
              audience: '新用户',
              status: 'ready',
              href: '/download',
            },
            {
              title: '登录与个人主页',
              body: '使用邮箱验证码或 Google 登录，登录后从头部账号菜单打开个人主页。',
              audience: '账号用户',
              status: 'preview',
              href: '/profile',
            },
            {
              title: 'FAQ 与隐私',
              body: '查看官网公开问题、数据边界和隐私说明，适合作为上线前的基础说明入口。',
              audience: '所有用户',
              status: 'ready',
              href: '/faq',
            },
          ],
        },
        {
          title: '产品能力',
          intro: '说明 ZenMind Desktop、模型生态和跨端方向，帮助用户理解产品边界。',
          cards: [
            {
              title: 'Desktop 工作台',
              body: 'Desktop shell 统一管理本地服务、Agent 运行时、日志和健康状态。',
              audience: '桌面端用户',
              status: 'preview',
              href: externalLinks.architecture,
            },
            {
              title: '模型支持',
              body: '了解 provider registry、模型能力、用量映射和模型生态优先级。',
              audience: '模型使用者',
              status: 'preview',
              href: externalLinks.models,
            },
            {
              title: '移动端方向',
              body: '移动端将复用 AGW UI 协议，与 Desktop/Web 共享同一套 Agent 体验。',
              audience: '跨端用户',
              status: 'soon',
              href: externalLinks.mobile,
            },
          ],
        },
        {
          title: '开发与集成',
          intro: '面向开发者和管理员，解释协议、沙箱、技能、插件以及未来市场能力。',
          cards: [
            {
              title: '架构说明',
              body: '查看 Desktop、App Server、Agent Platform、Web Client 与 Container Hub 的职责边界。',
              audience: '开发者',
              status: 'ready',
              href: externalLinks.architecture,
            },
            {
              title: 'AGW UI 协议',
              body: '客户端与 Agent Platform 之间的事件模型、流式传输、HITL 与 viewport 契约。',
              audience: '协议开发者',
              status: 'preview',
              href: externalLinks.agwui,
            },
            {
              title: '能力市场说明',
              body: '查看技能、沙箱、插件、模型 Provider 和工作流模板的公开展示方式。',
              audience: '扩展开发者',
              status: 'preview',
              href: '/market',
            },
          ],
        },
      ],
    },
    download: {
      eyebrow: 'Download',
      title: '下载 ZenMind',
      intro: '选择你的平台下载安装 ZenMind Desktop。推荐入口会根据当前系统提示，但平台顺序保持固定。',
      recommendation: {
        eyebrow: '推荐下载',
        titlePrefix: '推荐下载',
        unavailableTitle: '当前平台暂未开放安装包',
        unavailableBody: '你仍然可以查看文档或源码，了解 ZenMind Desktop 的安装与运行方式。',
        unknownLabel: '当前系统',
      },
      platformsTitle: '选择平台',
      recommendedBadge: '推荐',
      detailsLabel: '安装说明',
      docsCta: '查看文档',
      sourceCta: '查看源码',
      desktop: {
        eyebrow: 'Desktop',
        title: '下载 ZenMind 桌面版',
        intro: '安装桌面版后统一管理本地服务、Agent 运行时、日志与健康状态。',
        visualTitle: 'ZenMind Desktop',
        visualRows: ['服务中心', 'Agent 运行时', '本地沙箱', '跨端入口'],
      },
      mobile: {
        eyebrow: 'Mobile',
        title: '下载 ZenMind 移动版',
        intro: '移动端正在规划中，将继续复用 AGW UI 协议与 Desktop-first 工作流。',
        status: '敬请期待',
        visualTitle: 'ZenMind Mobile',
        visualRows: ['对话续接', '任务状态', '移动工作流'],
      },
    },
    news: {
      eyebrow: 'News',
      title: '新闻',
      intro: '这里同时展示 ZenMind 产品动态和 AI 行业观察。产品动态来自官网路线，行业观察链接到官方来源，不做实时新闻抓取。',
      productTitle: '产品动态',
      productIntro: '围绕官网、桌面端、账号入口和能力市场的公开进展。',
      industryTitle: 'AI 行业观察',
      industryIntro: '关注模型能力、Agent 工作流、本地运行和企业 AI 工具化趋势。',
      sourceLabel: '官方来源',
      productUpdates: [
        {
          phase: '官网',
          title: '官网入口重组为文档、新闻、市场、下载',
          body: '顶部导航围绕公开门户重新排序，下载、登录、个人主页和管理员入口的职责更加清晰。',
          status: 'ready',
        },
        {
          phase: '账号',
          title: '个人主页成为登录后的用户入口',
          body: '普通用户登录后仍停留在官网，点击个人主页后在新标签页查看账号状态和模型 API 用量占位。',
          status: 'preview',
        },
        {
          phase: '市场',
          title: '功能市场按技能、沙箱、插件组织',
          body: '市场页先做静态展示，后续可逐步承接技能包、沙箱模板、插件和工作流模板。',
          status: 'preview',
        },
      ],
      industryTrends: [
        {
          phase: '模型',
          title: '前沿模型继续向推理、多模态和工具调用演进',
          body: '模型厂商持续把推理能力、长上下文、多模态输入和工具调用作为核心产品方向。',
          href: externalLinks.openAiNews,
          source: 'OpenAI News',
        },
        {
          phase: 'Agent',
          title: 'Agent 产品开始强调可控流程和人工确认',
          body: '从单次对话走向可恢复、可确认、可观测的任务流，是企业和开发者工具的重要趋势。',
          href: externalLinks.anthropicNews,
          source: 'Anthropic News',
        },
        {
          phase: '多模态',
          title: 'AI 入口从文本对话扩展到搜索、设备和工作流',
          body: 'AI 能力正在嵌入搜索、浏览器、办公、移动设备和开发工具，入口形态更加分散。',
          href: externalLinks.googleAiBlog,
          source: 'Google AI Blog',
        },
        {
          phase: '本地运行',
          title: '本地算力和个人 AI 设备推动桌面端重新变重要',
          body: '桌面端和本地运行时能承接隐私、低延迟、工具执行和本地文件场景。',
          href: externalLinks.nvidiaAiNews,
          source: 'NVIDIA News',
        },
      ],
    },
    market: {
      eyebrow: 'Market',
      title: '功能市场',
      intro: 'ZenMind 市场先按能力类型展示：技能、沙箱、插件、模型 Provider 和工作流模板。每个能力标注适用任务，当前不执行在线安装。',
      sectionLabel: '能力分类',
      taskLabel: '适用任务',
      actionLabel: '查看说明',
      categories: [
        {
          key: 'skills',
          title: '技能',
          status: 'preview',
          body: '面向文档、表格、PDF、PPT 与开发任务的能力包，按需进入 Agent 上下文。',
          taskTags: ['文档', '数据', '开发'],
          items: ['Office 自动化', '项目说明加载', '长文档处理'],
          href: '/documents',
        },
        {
          key: 'sandboxes',
          title: '沙箱',
          status: 'soon',
          body: '为长期任务和工具执行准备隔离环境模板，服务本地 agent-container-hub。',
          taskTags: ['本地运行时', '自动化', '隔离执行'],
          items: ['容器工具运行时', '会话模板', '资源边界'],
          href: externalLinks.architecture,
        },
        {
          key: 'plugins',
          title: '插件',
          status: 'soon',
          body: '扩展 Desktop、Web Client 或 Agent Platform 的工具、面板与工作流入口。',
          taskTags: ['工作流', '第三方工具', '服务面板'],
          items: ['服务面板', '快捷工作流', '第三方工具桥接'],
          href: '/documents',
        },
        {
          key: 'models',
          title: '模型 / Provider',
          status: 'preview',
          body: '把不同模型供应商、模型能力、计费用量和调用偏好组织成可维护的 registry。',
          taskTags: ['模型调用', '用量统计', 'Provider'],
          items: ['DeepSeek', 'Qwen / Bailian', 'MiniMax / MiMo'],
          href: externalLinks.models,
        },
        {
          key: 'workflows',
          title: '工作流模板',
          status: 'soon',
          body: '把常见任务沉淀为可复用模板，例如文档分析、代码审查、数据整理和自动化运维。',
          taskTags: ['模板', '自动化', '团队协作'],
          items: ['文档分析', '代码审查', '数据整理'],
          href: '/documents',
        },
      ],
    },
    login: {
      eyebrow: 'Login',
      title: '登录 ZenMind',
      intro: '使用邮箱验证码或 Google 账号继续。',
      portalTitle: '登录 ZenMind',
      portalBody: '使用邮箱验证码或 Google 账号继续。',
      highlights: ['邮箱验证码', 'Google 登录', '安全会话'],
      formTitle: '邮箱验证码登录',
      emailLabel: '邮箱',
      codeLabel: '6 位验证码',
      codePlaceholder: '请输入验证码',
      sendCode: '发送验证码',
      resendCode: '重新发送',
      codeSent: '验证码已发送，请查看邮箱。',
      verifySubmit: '登录 / 注册',
      separator: '或',
      passwordLabel: '密码',
      adminLoginTitle: '管理员密码登录',
      adminLoginSummary: '已有管理员账号可继续使用密码登录。',
      submit: '管理员登录',
      googleSubmit: '使用 Google 登录',
      submitting: '处理中',
      sendingCode: '发送中',
      verifyingCode: '验证中',
      checking: '检查会话',
      signedIn: '已登录',
      signedOut: '未登录',
      welcome: '当前账号',
      profileCta: '打开个人主页',
      homeCta: '返回首页',
      accountLabel: '账号',
      roleLabel: '角色',
      providerLabel: '登录方式',
      logout: '退出登录',
      sessionTitle: '安全登录',
      sessionBody: '支持邮箱验证码登录即注册，也可以继续使用 Google 登录。',
      errorFallback: '请求失败，请稍后重试。',
    },
    profile: {
      eyebrow: 'Profile',
      title: '个人主页',
      intro: '查看你的账号状态、ZenMind 使用概览和模型 API 消耗。',
      accountTitle: '账号概览',
      usageTitle: '模型 API 用量',
      trendsTitle: '近 7 天趋势',
      providersTitle: 'Provider 分布',
      settingsTitle: '账号设置',
      settingsBody: '个人资料、登录方式和安全设置会在后续版本开放编辑。',
      loginPromptTitle: '请先登录',
      loginPromptBody: '登录后可以查看个人主页、账号状态和用量概览。',
      signInCta: '前往登录',
      fields: {
        email: '邮箱',
        role: '角色',
        provider: '登录方式',
        status: '状态',
      },
      metrics: {
        calls: '本月调用',
        tokens: '本月 token',
        cost: '费用估算',
        recentModel: '最近模型',
      },
      emptyMetric: '准备中',
    },
    adminLogin: {
      eyebrow: 'Admin',
      title: '管理员登录',
      intro: '请输入管理员账号信息继续。',
      portalTitle: '管理员入口',
      portalBody: '用于查看全站用量、下载统计和管理员概览。管理员权限必须由服务端校验。',
      highlights: ['全站模型 API 用量', '用户与下载统计', '服务端权限校验'],
      emailLabel: '管理员邮箱',
      passwordLabel: '管理员密码',
      submit: '进入管理后台',
      submitting: '登录中',
      securityNote: '管理员权限由服务端校验。',
      errorFallback: '管理员登录失败，请稍后重试。',
    },
    admin: {
      eyebrow: 'Admin',
      title: '管理后台',
      intro: '查看全站用量、下载统计和管理员概览。',
      loginRequiredTitle: '需要管理员登录',
      loginRequiredBody: '请先通过管理员入口登录。',
      loginCta: '前往管理员登录',
      noPermissionTitle: '当前账号没有管理员权限',
      noPermissionBody: '请使用管理员账号登录后再访问该页面。',
      overviewTitle: '全站概览',
      trendsTitle: '全站用量趋势',
      metrics: {
        calls: '全站调用',
        tokens: '全站 token',
        cost: '费用估算',
        users: '活跃用户',
        downloads: '下载统计',
        providers: 'Provider 分布',
      },
      activityTitle: '最近活动',
    },
    authFailure: {
      eyebrow: 'OAuth Failure',
      title: 'Google 登录未完成',
      intro: '这次 Google 授权没有成功建立 ZenMind 会话。你可以重新登录，或先返回首页。',
      status: '登录失败',
      reasonLabel: '错误码',
      unknownReason: 'unknown',
      reasonHelp: '如果连续出现同一个错误码，请联系管理员检查 Google OAuth 配置和服务端日志。',
      loginCta: '返回登录',
      homeCta: '返回首页',
    },
    footer: {
      rights: 'All rights reserved.',
      source: '主仓库',
    },
  },
  en: {
    code: 'en',
    switchLabel: '中',
    brandMark: 'ZenMind',
    seo: {
      title: 'ZenMind | Desktop-first AI Agent Platform',
      description:
        'ZenMind is a Desktop-first AI agent platform for local services, web and mobile workflows, Chinese model ecosystems, and local sandboxes.',
      url: `${siteUrl}/en`,
    },
    nav: {
      home: 'Home',
      download: 'Download',
      documents: 'Documents',
      news: 'News',
      market: 'Market',
      login: 'Login',
      adminLogin: 'Admin login',
      profile: 'Profile',
      admin: 'Admin',
      authFailure: 'Sign-in failure',
      github: 'GitHub',
    },
    theme: {
      label: 'Theme',
      auto: 'Auto',
      light: 'Light',
      dark: 'Dark',
    },
    shared: {
      copyLabel: 'Copy',
      copiedLabel: 'Copied',
      openGithub: 'GitHub',
      readDocs: 'Read docs',
      deployDocs: 'Deploy entry',
      downloadDesktop: 'Download',
      openProfile: 'Profile',
      logout: 'Log out',
      currentAccount: 'Current account',
      notSignedIn: 'Not signed in',
      noPermission: 'No permission',
      usagePreparing: 'Usage data is being prepared',
      statusReady: 'Available',
      statusSoon: 'Planned',
      statusPreview: 'Preview',
      externalLabel: 'Open external link',
      downloadFallback: 'Read docs',
      downloadTotalPrefix: '',
      downloadTotalSuffix: ' downloads',
    },
    home: {
      eyebrow: 'Desktop-first AI Agent Platform',
      headline: 'Enter your AI Agent workflow from desktop',
      heroIntro:
        'ZenMind organizes the desktop app, local services, model providers, sandbox runtime, and capability market into one work entry for long-running tasks, document work, and controllable agent workflows.',
      primaryCta: 'Read docs',
      secondaryCta: 'Login / Profile',
      downloadUnavailableTitle: 'No Desktop installer for this environment yet',
      downloadUnavailableBody: 'You can still read the docs or browse the source to understand ZenMind Desktop, core services, and local sandboxing.',
      heroStats: [
        { value: 'Desktop', label: 'Install, start, and monitor' },
        { value: 'AGW UI', label: 'Streaming, HITL, viewport' },
        { value: 'Sandbox', label: 'Long-lived tool environments' },
      ],
      consoleTitle: 'ZenMind runtime',
      consoleLines: [
        'desktop: service center ready',
        'app-server: token bridge online',
        'agent-platform: AGW stream attached',
        'container-hub: sandbox session prepared',
      ],
      featuresEyebrow: 'Core features',
      featuresTitle: 'Core capabilities at a glance',
      featuresIntro: 'A scan-friendly view of Desktop, Agent UI, models, sandboxes, and market capabilities.',
      portalEyebrow: 'Portal',
      portalTitle: 'What do you want to do?',
      portalIntro: 'The homepage is both a product introduction and a direct entry into the right website area.',
      portalEntries: [
        {
          key: 'documents',
          title: 'Documents',
          body: 'Product usage, developer integration, AGW UI, models, and sandbox notes.',
          href: '/en/documents',
        },
        {
          key: 'news',
          title: 'News',
          body: 'Product updates and AI industry observations.',
          href: '/en/news',
        },
        {
          key: 'market',
          title: 'Market',
          body: 'Skills, sandboxes, plugins, model providers, and workflow templates.',
          href: '/en/market',
        },
        {
          key: 'download',
          title: 'Download',
          body: 'Install the desktop app for your platform.',
          href: '/en/download',
        },
        {
          key: 'profile',
          title: 'Profile',
          body: 'Open account status and usage placeholders after login.',
          href: '/en/profile',
        },
      ],
      capabilityCards: [
        {
          key: 'desktop',
          title: 'Desktop',
          body: 'Install, start, monitor, and configure from one place.',
        },
        {
          key: 'agent',
          title: 'Agent UI',
          body: 'Streaming output, human confirmation, and recoverable tasks.',
        },
        {
          key: 'models',
          title: 'Models',
          body: 'Model providers, capability flags, and usage tracking.',
        },
        {
          key: 'sandbox',
          title: 'Sandbox',
          body: 'Long-running tasks and tool execution environments.',
        },
        {
          key: 'market',
          title: 'Market',
          body: 'Skills, plugins, and workflow template entries.',
        },
      ],
      featureSections: [
        {
          key: 'desktop',
          title: 'One Desktop app manages the runtime',
          body:
            'ZenMind Desktop installs, initializes, starts, stops, monitors service health, and embeds web surfaces so users enter every capability from one control center.',
          points: ['Service lifecycle', 'Logs and settings', 'Token bridge'],
          visualTitle: 'Desktop Control Center',
          visualRows: ['Install bundled services', 'Start agent runtime', 'Watch logs and health'],
        },
        {
          key: 'models',
          title: 'Runtime registry for Chinese model ecosystems',
          body:
            'ZenMind prioritizes DeepSeek V4, MiMo, MiniMax M3, Qwen/Bailian, and keeps providers, model capabilities, and usage fields extensible.',
          points: ['Model switching', 'Reasoning and vision flags', 'token/cache/cost usage'],
          visualTitle: 'Model Registry',
          visualRows: ['DeepSeek V4', 'MiMo', 'MiniMax M3', 'Qwen / Bailian'],
        },
        {
          key: 'agw',
          title: 'AGW UI carries real agent interaction',
          body:
            'AGW UI combines HTTP, SSE, and optional WebSocket transport for streaming output, attach recovery, HITL, viewports, usage snapshots, and sub-agent invocation.',
          points: ['H2A streaming', 'question / approval / form / plan', 'agent_invoke'],
          visualTitle: 'AGW UI Stream',
          visualRows: ['stream delta', 'await approval', 'render viewport', 'usage snapshot'],
        },
        {
          key: 'sandbox',
          title: 'Local sandboxes keep tools and office work running',
          body:
            'agent-container-hub provides local sandbox sessions, environment templates, and container-backed tool runtimes for documents, sheets, PDFs, and slides.',
          points: ['Long-lived sessions', 'Tool environment templates', 'Office skill paths'],
          visualTitle: 'Local Sandbox',
          visualRows: ['container session', 'tool runtime', 'DOCX / XLSX / PDF / PPT'],
        },
        {
          key: 'clients',
          title: 'One agent experience across Desktop, Web, and Mobile',
          body:
            'Desktop is the entry point. Web Client renders chat, timeline, model switching, and viewports. Mobile direction reuses AGW UI instead of a separate agent contract.',
          points: ['Desktop first', 'Web timeline', 'Mobile direction'],
          visualTitle: 'One Agent Contract',
          visualRows: ['Desktop', 'Web Client', 'Mobile direction'],
        },
      ],
      finalCtaTitle: 'Start using ZenMind',
      finalCtaBody: 'Download the desktop app, or explore docs and market capabilities first.',
      footerTagline: 'Desktop-first AI Agent platform for local, web, and mobile workflows.',
    },
    documents: {
      eyebrow: 'Documents',
      title: 'Documents',
      intro:
        'A combined software and developer documentation entry: start with download, login, and product usage, then continue into architecture, protocols, models, sandboxes, and market capabilities.',
      sectionLabel: 'Doc sections',
      audienceLabel: 'For',
      actionLabel: 'View docs',
      docSections: [
        {
          title: 'Get started',
          intro: 'For first-time ZenMind users: download, login, profile, and public FAQ.',
          cards: [
            {
              title: 'Download and install',
              body: 'Choose the desktop installer for your platform and review the current macOS, Windows, and Linux status.',
              audience: 'New users',
              status: 'ready',
              href: '/en/download',
            },
            {
              title: 'Login and profile',
              body: 'Sign in with an email code or Google, then open your profile from the account menu in a new tab.',
              audience: 'Account users',
              status: 'preview',
              href: '/en/profile',
            },
            {
              title: 'FAQ and privacy',
              body: 'Review public questions, data boundaries, and privacy notes before rollout.',
              audience: 'All users',
              status: 'ready',
              href: '/en/faq',
            },
          ],
        },
        {
          title: 'Product capabilities',
          intro: 'Understand ZenMind Desktop, model support, and cross-client direction.',
          cards: [
            {
              title: 'Desktop workspace',
              body: 'Desktop shell manages local services, agent runtime, logs, and health status from one place.',
              audience: 'Desktop users',
              status: 'preview',
              href: externalLinks.architecture,
            },
            {
              title: 'Model support',
              body: 'Read about provider registry, model capabilities, usage mapping, and model ecosystem priorities.',
              audience: 'Model users',
              status: 'preview',
              href: externalLinks.models,
            },
            {
              title: 'Mobile direction',
              body: 'Mobile will reuse AGW UI and share the same agent experience with Desktop and Web.',
              audience: 'Cross-client users',
              status: 'soon',
              href: externalLinks.mobile,
            },
          ],
        },
        {
          title: 'Develop and integrate',
          intro: 'For developers and administrators: protocols, sandboxes, skills, plugins, and future market capabilities.',
          cards: [
            {
              title: 'Architecture',
              body: 'Review responsibilities across Desktop, App Server, Agent Platform, Web Client, and Container Hub.',
              audience: 'Developers',
              status: 'ready',
              href: externalLinks.architecture,
            },
            {
              title: 'AGW UI Protocol',
              body: 'Event model, streaming transport, HITL states, and viewport contract between clients and Agent Platform.',
              audience: 'Protocol developers',
              status: 'preview',
              href: externalLinks.agwui,
            },
            {
              title: 'Market capabilities',
              body: 'Review how skills, sandboxes, plugins, model providers, and workflow templates are presented publicly.',
              audience: 'Extension developers',
              status: 'preview',
              href: '/en/market',
            },
          ],
        },
      ],
    },
    download: {
      eyebrow: 'Download',
      title: 'Download ZenMind',
      intro: 'Choose your platform to install ZenMind Desktop. The recommendation follows your current system while the platform order stays fixed.',
      recommendation: {
        eyebrow: 'Recommended',
        titlePrefix: 'Recommended for',
        unavailableTitle: 'No installer is available for this platform yet',
        unavailableBody: 'You can still read the docs or browse the source to understand how ZenMind Desktop runs.',
        unknownLabel: 'Current system',
      },
      platformsTitle: 'Choose a platform',
      recommendedBadge: 'Recommended',
      detailsLabel: 'Install notes',
      docsCta: 'Read docs',
      sourceCta: 'View source',
      desktop: {
        eyebrow: 'Desktop',
        title: 'Download ZenMind Desktop',
        intro: 'Install the desktop app to manage local services, agent runtime, logs, and health from one place.',
        visualTitle: 'ZenMind Desktop',
        visualRows: ['Service center', 'Agent runtime', 'Local sandbox', 'Cross-client entry'],
      },
      mobile: {
        eyebrow: 'Mobile',
        title: 'Download ZenMind Mobile',
        intro: 'Mobile is planned and will continue to reuse AGW UI and the Desktop-first workflow.',
        status: 'Coming soon',
        visualTitle: 'ZenMind Mobile',
        visualRows: ['Chat continuity', 'Task status', 'Mobile workflow'],
      },
    },
    news: {
      eyebrow: 'News',
      title: 'News',
      intro:
        'Product updates and AI industry observations in one place. Product updates follow the ZenMind roadmap; industry observations link to official sources instead of live news scraping.',
      productTitle: 'Product updates',
      productIntro: 'Public progress around the website, desktop app, account entry, and capability market.',
      industryTitle: 'AI industry observations',
      industryIntro: 'Trends around model capability, agent workflows, local runtime, and enterprise AI tooling.',
      sourceLabel: 'Official source',
      productUpdates: [
        {
          phase: 'Website',
          title: 'Navigation reorganized around docs, news, market, and download',
          body: 'Public entry points now separate download, login, profile, and administrator access more clearly.',
          status: 'ready',
        },
        {
          phase: 'Account',
          title: 'Profile becomes the signed-in user entry',
          body: 'Users remain on the public website after login and open profile in a new tab from the account menu.',
          status: 'preview',
        },
        {
          phase: 'Market',
          title: 'Capability market organized by skills, sandboxes, and plugins',
          body: 'The market starts as a static showcase and can later host skills, sandbox templates, plugins, and workflow templates.',
          status: 'preview',
        },
      ],
      industryTrends: [
        {
          phase: 'Models',
          title: 'Frontier models continue moving toward reasoning, multimodality, and tool use',
          body: 'Model providers keep making reasoning ability, long context, multimodal input, and tool use core product directions.',
          href: externalLinks.openAiNews,
          source: 'OpenAI News',
        },
        {
          phase: 'Agents',
          title: 'Agent products increasingly emphasize controllable workflows and human confirmation',
          body: 'The important shift is from one-off chat to recoverable, confirmable, and observable task flows.',
          href: externalLinks.anthropicNews,
          source: 'Anthropic News',
        },
        {
          phase: 'Multimodal',
          title: 'AI entry points expand beyond chat into search, devices, and work tools',
          body: 'AI capabilities are being embedded into search, browsers, office tools, mobile devices, and developer tools.',
          href: externalLinks.googleAiBlog,
          source: 'Google AI Blog',
        },
        {
          phase: 'Local runtime',
          title: 'Local compute and personal AI devices make desktop runtime important again',
          body: 'Desktop and local runtimes support privacy, low latency, tool execution, and local file workflows.',
          href: externalLinks.nvidiaAiNews,
          source: 'NVIDIA News',
        },
      ],
    },
    market: {
      eyebrow: 'Market',
      title: 'Capability market',
      intro:
        'The ZenMind market starts with capability categories: skills, sandboxes, plugins, model providers, and workflow templates. Each item carries task tags; this page does not install capabilities yet.',
      sectionLabel: 'Capability categories',
      taskLabel: 'Tasks',
      actionLabel: 'View details',
      categories: [
        {
          key: 'skills',
          title: 'Skills',
          status: 'preview',
          body: 'Capability packages for documents, sheets, PDFs, slides, and development tasks that can enter agent context on demand.',
          taskTags: ['Documents', 'Data', 'Development'],
          items: ['Office automation', 'Project instructions', 'Long-document processing'],
          href: '/en/documents',
        },
        {
          key: 'sandboxes',
          title: 'Sandboxes',
          status: 'soon',
          body: 'Isolated environment templates for long-running tasks and tool execution through the local Container Hub.',
          taskTags: ['Local runtime', 'Automation', 'Isolated execution'],
          items: ['Container runtimes', 'Session templates', 'Resource boundaries'],
          href: externalLinks.architecture,
        },
        {
          key: 'plugins',
          title: 'Plugins',
          status: 'soon',
          body: 'Extensions for Desktop, Web Client, or Agent Platform surfaces: tools, panels, and workflow entry points.',
          taskTags: ['Workflows', 'Third-party tools', 'Service panels'],
          items: ['Service panels', 'Workflow shortcuts', 'Third-party tool bridges'],
          href: '/en/documents',
        },
        {
          key: 'models',
          title: 'Models / Providers',
          status: 'preview',
          body: 'Organize providers, model capabilities, usage accounting, and routing preferences in a maintainable registry.',
          taskTags: ['Model calls', 'Usage', 'Provider'],
          items: ['DeepSeek', 'Qwen / Bailian', 'MiniMax / MiMo'],
          href: externalLinks.models,
        },
        {
          key: 'workflows',
          title: 'Workflow templates',
          status: 'soon',
          body: 'Reusable task templates for document analysis, code review, data cleanup, and automation operations.',
          taskTags: ['Templates', 'Automation', 'Team workflows'],
          items: ['Document analysis', 'Code review', 'Data cleanup'],
          href: '/en/documents',
        },
      ],
    },
    login: {
      eyebrow: 'Login',
      title: 'Login to ZenMind',
      intro: 'Continue with an email code or Google account.',
      portalTitle: 'Login to ZenMind',
      portalBody: 'Continue with an email code or Google account.',
      highlights: ['Email code', 'Google sign-in', 'Secure session'],
      formTitle: 'Email code sign-in',
      emailLabel: 'Email',
      codeLabel: '6-digit code',
      codePlaceholder: 'Enter code',
      sendCode: 'Send code',
      resendCode: 'Send again',
      codeSent: 'Code sent. Check your inbox.',
      verifySubmit: 'Sign in / Register',
      separator: 'or',
      passwordLabel: 'Password',
      adminLoginTitle: 'Admin password login',
      adminLoginSummary: 'Existing administrator accounts can still use password login.',
      submit: 'Admin login',
      googleSubmit: 'Continue with Google',
      submitting: 'Working',
      sendingCode: 'Sending',
      verifyingCode: 'Verifying',
      checking: 'Checking session',
      signedIn: 'Signed in',
      signedOut: 'Signed out',
      welcome: 'Current account',
      profileCta: 'Open profile',
      homeCta: 'Back home',
      accountLabel: 'Account',
      roleLabel: 'Role',
      providerLabel: 'Method',
      logout: 'Log out',
      sessionTitle: 'Secure sign-in',
      sessionBody: 'Email codes sign you in and register new accounts automatically. Google sign-in remains available.',
      errorFallback: 'Request failed. Please try again.',
    },
    profile: {
      eyebrow: 'Profile',
      title: 'Profile',
      intro: 'View your account status, ZenMind usage overview, and model API consumption.',
      accountTitle: 'Account overview',
      usageTitle: 'Model API usage',
      trendsTitle: 'Last 7 days',
      providersTitle: 'Provider distribution',
      settingsTitle: 'Account settings',
      settingsBody: 'Profile, login method, and security editing will open in a later version.',
      loginPromptTitle: 'Sign in required',
      loginPromptBody: 'Sign in to view your profile, account status, and usage overview.',
      signInCta: 'Go to login',
      fields: {
        email: 'Email',
        role: 'Role',
        provider: 'Login method',
        status: 'Status',
      },
      metrics: {
        calls: 'Monthly calls',
        tokens: 'Monthly tokens',
        cost: 'Estimated cost',
        recentModel: 'Recent model',
      },
      emptyMetric: 'Preparing',
    },
    adminLogin: {
      eyebrow: 'Admin',
      title: 'Admin login',
      intro: 'Enter administrator account details to continue.',
      portalTitle: 'Administrator entry',
      portalBody: 'Use this entry to review site-wide usage, downloads, and administrator overview. Administrator access must be enforced by the server.',
      highlights: ['Site-wide model API usage', 'Users and downloads', 'Server-side permission checks'],
      emailLabel: 'Admin email',
      passwordLabel: 'Admin password',
      submit: 'Enter admin',
      submitting: 'Signing in',
      securityNote: 'Administrator access is verified by the server.',
      errorFallback: 'Admin login failed. Please try again later.',
    },
    admin: {
      eyebrow: 'Admin',
      title: 'Admin',
      intro: 'View site-wide usage, downloads, and administrator overview.',
      loginRequiredTitle: 'Admin login required',
      loginRequiredBody: 'Please sign in through the administrator entry first.',
      loginCta: 'Go to admin login',
      noPermissionTitle: 'This account does not have administrator access',
      noPermissionBody: 'Use an administrator account before opening this page.',
      overviewTitle: 'Site overview',
      trendsTitle: 'Site usage trend',
      metrics: {
        calls: 'Site calls',
        tokens: 'Site tokens',
        cost: 'Estimated cost',
        users: 'Active users',
        downloads: 'Downloads',
        providers: 'Provider distribution',
      },
      activityTitle: 'Recent activity',
    },
    authFailure: {
      eyebrow: 'OAuth Failure',
      title: 'Google sign-in did not finish',
      intro: 'Google authorization did not create a ZenMind session this time. You can try signing in again or return home.',
      status: 'Sign-in failed',
      reasonLabel: 'Error code',
      unknownReason: 'unknown',
      reasonHelp: 'If the same error code keeps appearing, ask an administrator to check Google OAuth settings and server logs.',
      loginCta: 'Back to login',
      homeCta: 'Back home',
    },
    footer: {
      rights: 'All rights reserved.',
      source: 'Source repo',
    },
  },
};

export { githubUrl, siteUrl };
